FROM mcr.microsoft.com/vscode/devcontainers/base:focal


RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    build-essential cmake cppcheck valgrind man manpages-posix-dev \
    manpages-posix bsdmainutils glibc-source netcat ltrace strace sudo \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/*